### ISSUE TITLE
IPv6 Support for marshalSANs Function

### ISSUE THREAD

**Issue by danehans** [google/certificate-transparency-go#12]
I am working on adding IPv6 to [Kubernetes](https://kubernetes.io/). I found that Kubernetes has a dependency on the x509 pkg. In reviewing this pkg, the marshalSANs [function](https://github.com/google/certificate-transparency-go/blob/master/x509/x509.go#L1557) does not support IPv6 addresses. Will you accept a pull request that updates this function for IPv6?

**Comment by rolandshoemaker** [comment]
I suspect you are in the wrong place, this is a fork of the Golang stdlib x509 package (the repo for which is [here](https://github.com/golang/go)).

That said `marshalSANs` _does_ support IPv6 addresses, by default Golang will represent both IPv4 and IPv6 addresses using 16 bytes, the code you are looking at is simply trying to use the minimal number of bytes to encode v4 addresses when possible by using `To4()` which returns a four byte slice instead of the default 16. In the case where the address isn't IPv4 (if `To4() == nil`) it just uses the initial 16 byte address.

**Comment by daviddrysdale** [comment]
What Roland said (and on a quick look at the [Kubernetes source](https://github.com/kubernetes/kubernetes), it looks like they're using the standard library `crypto/x509` rather than our fork of it).

Feel free to re-open if we've missed something though.

**Comment by danehans** [comment]
Thanks for your help.
