### ISSUE TITLE
asn1, x509 questions

### ISSUE THREAD

**Issue by kumarde** [google/certificate-transparency-go#4]
Hi,

There are large numbers of certs that come from CT logs that the current x509/ASN1 golang libraries are not able to parse. In the worst case, ~10% of the skydiver certs don't parse correctly, all due to the same error. You can replicate with an example cert here: https://play.golang.org/p/IL-Ey-fSXt

This behavior is both in the golang crypto/x509 package and the ct x509 package - does anyone have any ideas as to why this would happen? 

Thanks!

**Comment by daviddrysdale** [comment]
It doesn't parse as a certificate because it's not a certificate -- it's a [precertificate](https://tools.ietf.org/html/rfc6962#section-3.1).  Dealing with them can be a bit fiddly, partly because of the asymmetry of submission/retrieval:
 - A precert is added to a log with the [add-pre-chain](https://tools.ietf.org/html/rfc6962#section-4.2) entrypoint, and this takes the precert in the form of a full X.509 certificate, including a signature from the issuer (so the issuer is commiting to the cert) but also including a 'poison' critical extension (so the submitted entry is not itself a valid cert).
 - When a precert is [retrieved from the log](https://tools.ietf.org/html/rfc6962#section-4.6), it comes back inside a [`MerkleTreeLeaf`](https://tools.ietf.org/html/rfc6962#section-3.4) structure, as a [`PreCert`](https://tools.ietf.org/html/rfc6962#section-3.2) structure.  This isn't in the form of a full X.509 cert; it just has the inner `TBSCertificate`.

So the example you've got looks like just the inner `TBSCertificate`, and there will be lots of other examples of these in the logs -- try using `x509.ParseTBSCertificate` instead.

**Comment by kumarde** [comment]
@daviddrysdale thanks for the response! So it is _necessarily_ the case that a Precert pulled from a CT log will never have the signature or signatureValue fields, and only the TBSCertificate?

**Comment by daviddrysdale** [comment]
That's what's defined to be in the `MerkleTreeLeaf` itself, and what gets hashed over.  However, the `get-entries` response does also [have](https://tools.ietf.org/html/rfc6962#section-4.6) an `extra_data` field with a `PrecertChainEntry` in it, and [that has](https://tools.ietf.org/html/rfc6962#section-3.1) the submitted `pre_certificate` in it.
