### ISSUE TITLE
Massive amounts of 429 errors in the log

### ISSUE THREAD

**Issue by d-Rickyy-b** [google/certificate-transparency-go#957]
Hi there,

when I run my certificate monitoring service for a few minutes, I start receiving massive amounts of http 429 errors. According to #746, a backoff mechanism has been implemented already. What else can I do to avoid 1) massive 429 errors and 2) the spam in my logs.

![grafik](https://user-images.githubusercontent.com/5798157/180645920-8b572cbe-cc4c-4037-997b-82c6b66b4950.png)

Cheers,
Rico

**Comment by mhutchinson** [comment]
There are a number of options you could try. The first is reducing the number of parallel workers. Otherwise, changing code in your version of `scanner/fetcher.go` to tune your experience opens more options. In `runWorker`:
 * Changing the parameters for the `backoff.Backoff`; I'd recommend increasing the `Min` to a larger number, and increasing the `Factor` should also make the backoffs longer
 * Removing the `glog.Errorf` on line 287, or downgrading it to `glog.V(1).Infof` so you still have the option of seeing the errors

**Comment by d-Rickyy-b** [comment]
Hi @mhutchinson and thanks for your reply!

If I understood you correctly, both of these options require me to change the code of this module, right?
I'm using certificate-transparency-go as a dependency and am using the JSONClient. The backoff attribute is private and can't be manipulated from the outside. The code in runWorker is also private and can't be modified.

https://github.com/google/certificate-transparency-go/blob/6ecca400d5e42ae3f26ad5c27cea9f907474024d/jsonclient/client.go#L150-L157

Is there any way for me as a user to solve (or circumvent) the issue?

**Comment by mhutchinson** [comment]
The PR I've just merged will downgrade these 429 errors to info messages at verbosity level 2. If you don't override the `--v` argument that configures `glog` then you won't see this if you use a build that includes my change.
